language: node_js

node_js:
  - 12

cache:
  directories:
    - node_modules

# build life cycle
install:
  - npm install

before script:

script:
  - npm run build

after script:
  - set -e
  - cd docs/.vuepress/dist
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git add .
  - git commit -m "update jacen's blog"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GITHUB_REPO}" master
